IW | Requests for login, reg and store
frontend-park-mail-ru/2020_2_Friends pull request #14
Opened 2020-10-06 16:30 UTC by Scotfarel

requests in work

2020-10-06 19:08 UTC, gavroman requested changes

2020-10-06 19:08 UTC, gavroman commented on src/controller/storeController.js
> +    constructor (root, storeData) {
давай уберем данные из вьюхи, мокать все будем в модели, а со вьюхой взаимодействовать через `eventBus`

2020-10-06 19:08 UTC, gavroman commented on src/index.js
> +const storeData = getStoreDataRequest(0);
давай вынесем это в модель магазина

2020-10-06 19:08 UTC, gavroman commented on src/utils/ajax.js
> +    const parsedJsonObject = await response.json();
это может упасть, если не будет тела, предлагаю ворзвращать весь промис, который даст фетч

2020-10-07 08:32 UTC, Scotfarel commented on src/controller/storeController.js
> +    constructor (root, storeData) {
перенес

2020-10-07 08:32 UTC, Scotfarel commented on src/index.js
> +const storeData = getStoreDataRequest(0);
вынес

2020-10-18 19:15 UTC, merged