Merge branch
frontend-park-mail-ru/2020_2_Friends pull request #15
Opened 2020-10-06 23:48 UTC by naysudes

2020-10-07 07:28 UTC, gavroman requested changes

2020-10-07 07:28 UTC, gavroman commented on src/index.js
> +// import { getStoreDataRequest } from './utils/ApiService.js';
не оставляем ненужный коментов

2020-10-07 07:28 UTC, gavroman commented on src/utils/router.js
> +    redirect =  (to) => {
давайте будем юзать 1 вид функций в 1 файле, в классе чаще всего используют обычные функции

2020-10-07 07:28 UTC, gavroman commented on src/view/storeView.js
> +    render = (data) => {
давайте будем юзать 1 вид функций в 1 файле, в классе чаще всего используют обычные функции

2020-10-07 07:28 UTC, gavroman commented on src/view/registerView.js
> +            let isValid = true;
давайте вынесем валидацию в модель и будем отправлять ей значения инпутов через eventbus

2020-10-07 07:28 UTC, gavroman commented on src/view/registerView.js
> +    render = () => {
render() {}

2020-10-07 07:28 UTC, gavroman commented on src/view/profileView.js
>          });
почему здесь остались захардкоженные данные, они должны получаться с бека

2020-10-07 07:28 UTC, gavroman commented on src/view/profileView.js
> +            loginErrors.innerText = '';
надо вынести всю валидацию с модель

2020-10-07 07:28 UTC, gavroman commented on src/index.js
>  router.setRoute('register', regController);
вы хотели хендлеры закидывать в мапку роутера, а продолжаете закидывать контроллеры

2020-10-07 07:28 UTC, gavroman commented on src/utils/router.js
> +        this.routes.get(to)();
в мапке же лежат контроллеры, а вы пытаетесь их вызвать

2020-10-07 07:28 UTC, gavroman commented on src/utils/validator.js
> +        return { status: false, message: `${helpText}` };
зачем передавать `helpText` если он просто возвращается

2020-10-07 07:28 UTC, gavroman commented on src/view/loginView.js
> +    render = () => {
render() {}

2020-10-07 07:28 UTC, gavroman commented on src/view/loginView.js
> +                this.eventBus.call('REDITECT_TO_PROFILE');
Редирект должна делать моделька, если с бека пришел соответствующий ответ, тем более `this.eventBus.call()` всегда возвращает `undefined` и этот ифак никогда не сработает

2020-10-07 08:38 UTC, Scotfarel commented on src/utils/router.js
> +    redirect =  (to) => {
на счет  render() и redirect() - вчера только после превращения этих функций в стрелочные функции заработали корректно асинхронные вопросы, это было связано с контекстом при использовании асинхронных запросов

2020-10-14 19:21 UTC, naysudes commented on src/view/loginView.js
> +                this.eventBus.call('REDITECT_TO_PROFILE');
+

2020-10-14 19:47 UTC, naysudes commented on src/utils/validator.js
> +        return { status: false, message: `${helpText}` };
+

2020-10-14 19:47 UTC, naysudes commented on src/index.js
>  router.setRoute('register', regController);
+

2020-10-14 22:12 UTC, naysudes commented on src/utils/router.js
> +    redirect =  (to) => {
+

2020-10-14 22:12 UTC, naysudes commented on src/index.js
> +// import { getStoreDataRequest } from './utils/ApiService.js';
+

2020-10-14 22:12 UTC, naysudes commented on src/view/storeView.js
> +    render = (data) => {
+

2020-10-14 22:13 UTC, naysudes commented on src/view/registerView.js
> +    render = () => {
+

2020-10-14 22:13 UTC, naysudes commented on src/utils/router.js
> +        this.routes.get(to)();
+

2020-10-14 22:14 UTC, naysudes commented on src/view/loginView.js
> +    render = () => {
+

2020-10-15 08:38 UTC, gavroman requested changes

2020-10-15 08:38 UTC, gavroman commented on package.json
> -    "eslint": "^7.10.0",
ненене, линтер не только для первого рк нужон, не надо его выпиливать)

2020-10-15 08:38 UTC, gavroman commented on src/model/loginModel.js
>          cookieRequest();
что будет, если пароль не верный, или такого пользователя не существует? Тут должна появиться обработка ответа от бека, можно позже

2020-10-15 08:38 UTC, gavroman commented on src/model/loginModel.js
> +            this.eventBus.call('REDITECT_TO_PROFILE')
не очень понял этой логики, если логин с паролем валидный, мы редиректим в профиль? А на бек сходить, чтобы проверить верный ли пароль, куку получить?

2020-10-15 08:38 UTC, gavroman commented on src/view/loginView.js
> +            this.eventBus.call('VALIDATE', data);
давай здесь вызовем  `this.eventBus.call('SUBMIT_LOGIN', data);` , это отловит моделька, провалидирует и отошлет на бек если ок

2020-10-15 08:38 UTC, gavroman commented on src/model/profileModel.js
> +            console.log('logIN'); // eventBus.call('LOG_IN');
тут должен вызываться не логин, а другой конец, который отвечает за изменение пользовательских данных

2020-10-15 08:38 UTC, gavroman commented on src/model/profileModel.js
> +            console.log('logIN'); // eventBus.call('LOG_IN');
на самом деле эта функция может просто вернуть `true` или `false`, и в том месте где ее вызвали станет понятно валидно/невалидно, после чего можно вызывать что-то из eventBus

2020-10-15 08:38 UTC, gavroman commented on src/model/registerModel.js
> +            this.eventBus.call('SUBMIT_REG', input);
зачем тут вызов eventBus, функция, которую ты вызываешь лежит в том же классе, почему ее нельзя напрямую вызвать?

2020-10-15 20:19 UTC, Scotfarel commented on package.json
> -    "eslint": "^7.10.0",
странная фигня, у всех линтеры есть, они проходят

2020-10-15 20:20 UTC, Scotfarel commented on src/model/loginModel.js
>          cookieRequest();
да, это просто запрос сейчас для проверки кук бека, обработка чуть позже будет

2020-10-15 20:25 UTC, gavroman commented on package.json
> -    "eslint": "^7.10.0",
Потому что у всех вас пакет уже стоит. Снеси node_modules запусти npm install и не будут работать

2020-10-17 15:35 UTC, naysudes commented on src/model/profileModel.js
> +            console.log('logIN'); // eventBus.call('LOG_IN');
+

2020-10-17 15:35 UTC, naysudes commented on src/model/registerModel.js
> +            this.eventBus.call('SUBMIT_REG', input);
+

2020-10-18 19:08 UTC, gavroman commented on src/model/registerModel.js
> +            var errorString = 'Длина пароля от 8 до 30 символов<br/>Может содержать только латинские буквы и цифры';
вар

2020-10-18 19:15 UTC, merged