Izakharov/requests on promise
frontend-park-mail-ru/2020_2_Friends pull request #16
Opened 2020-10-19 21:40 UTC by Scotfarel

Rewrite ajax functions: return Promise instead parsed object.
Added cases at login and registration page associated with: https://docs.google.com/document/d/1Ul62MOHhA4epP9Hra3PTWvXmSD66iLSffNHiBMiv1_4/edit?usp=sharing

Another small fixes included.

2020-10-19 21:42 UTC, Scotfarel commented
Потребность была в замене старого аякса на возвращающий промисы.
В остальном - немного исправлений + обработок ответов сервера, готовимся делать страничку профиля.

2020-10-20 07:01 UTC, gavroman requested changes

2020-10-20 07:01 UTC, gavroman commented on src/model/loginModel.js
> +                console.log('Uncaught backend http-status');
думаю сюда отлично впишется `switch case`

2020-10-20 07:01 UTC, gavroman commented on src/model/registerModel.js
> +                console.log('Uncaught backend http-status');
switch case

2020-10-20 07:01 UTC, gavroman commented on src/utils/ajax.js
> +    return response;
зачем лишняя переменная, почему сразу не вернуть `fetch`

2020-10-20 07:01 UTC, gavroman commented on src/view/loginView.js
> +        eventBus.subscribe('SERVER_NOT_VALID', this.serverNotValid.bind(this));
давай все одинаково биндить, или так, или так как выше

2020-10-20 08:42 UTC, Scotfarel commented on src/model/loginModel.js
> +                console.log('Uncaught backend http-status');
согласен

2020-10-20 08:51 UTC, Scotfarel commented on src/utils/ajax.js
> +    return response;
исправил

2020-10-20 08:51 UTC, Scotfarel commented on src/view/loginView.js
> +        eventBus.subscribe('SERVER_NOT_VALID', this.serverNotValid.bind(this));
даже не заметил, как это написал вчера, исправил

2020-10-20 09:56 UTC, merged