Izakharov/avatar render
frontend-park-mail-ru/2020_2_Friends pull request #22
Opened 2020-10-22 22:04 UTC by Scotfarel

При загрузке аватарки перерендеривается только аватарка.

Так же добавил обработку всех кейсов магазина и профиля, на данных момент это только вывод сообщений об ошибках.

2020-10-22 22:47 UTC, Scotfarel commented
Ром, и я еще пытаюсь все таки прикрутить переходы по кнопкам "вперед-назад", на данный момент с реализацией как в последнем коммите он ходит только назад, и когда нажимаешь назад, он возвращает тебя сразу на страницу логина, а я стараюсь добиться нормального поведения.

Интернет посоветовал собственно заюзать onpopstate, но я дошел вот максимум до такого результата, как описал выше.

2020-10-23 07:32 UTC, gavroman requested changes

2020-10-23 07:32 UTC, gavroman commented on src/index.js
> +window.onload = function () {
ну рассказывай, чего это такое)

2020-10-23 07:32 UTC, gavroman commented on src/view/profileView.js
> +    }
4 +- одинаковые функции, го что-нибудь придумаем с этим

2020-11-04 13:17 UTC, gavroman commented on src/view/profileView.js
> +    }
так, теперь они вообще одинаковые) зачем?

2020-11-04 13:17 UTC, gavroman commented on src/index.js
> +console.log(url);
убираем лог

2020-11-04 13:25 UTC, gavroman approved these changes

2020-11-04 13:25 UTC, merged