делаем админку
frontend-park-mail-ru/2020_2_Friends pull request #25
Opened 2020-11-06 23:53 UTC by naysudes

Добавлены админские странички и урлы, взаимодействие с бэком не настроено

2020-11-07 08:53 UTC, gavroman requested changes

2020-11-07 08:53 UTC, gavroman commented on src/model/partnerProfileModel.js
> +                console.log(body);
убираем

2020-11-07 08:53 UTC, gavroman commented on src/model/partnerProfileModel.js
> +                    avatarUrl = makeAvatarUrl(body.avatar);
давай тернарник сюда

2020-11-07 08:53 UTC, gavroman commented on src/model/profileModel.js
> +            console.log(body);
убираем

2020-11-07 08:53 UTC, gavroman commented on src/template/partnerLoginViewTemplate.js
> +</div>`
чет поехало тут

2020-11-07 08:53 UTC, gavroman commented on src/template/headerViewTemplate.js
> +`)
; и \n

2020-11-07 08:53 UTC, gavroman commented on src/template/partnerLoginViewTemplate.js
> +)
; и \n

2020-11-07 08:53 UTC, gavroman commented on src/template/partnerProfileViewTemplate.js
> +`)
; и \n

2020-11-07 08:53 UTC, gavroman commented on src/template/partnerRegisterViewTemplate.js
> +)
; и \n

2020-11-07 08:53 UTC, gavroman commented on src/utils/ApiService.js
> +// }
а это почему так?

2020-11-07 08:53 UTC, gavroman commented on src/utils/ApiService.js
> + * Creating http login request via ajax methods.
кажется это не логин реквест) и дальше тоже комменты не соответствуют

2020-11-07 08:53 UTC, gavroman commented on src/utils/ApiService.js
> + * @param {object} id - Arguments that contains part of url for request.
`id` точно object? кажется тут больше `number` или `string`

2020-11-07 08:53 UTC, gavroman commented on src/utils/ApiService.js
> + * @param {object} id - Arguments that contains part of url for request.
+ описание

2020-11-07 08:53 UTC, gavroman commented on src/utils/ApiService.js
> + * @param {object} avatarName - Picture name for request.
тут тоже явно не `object`

2020-11-07 08:53 UTC, gavroman commented on src/utils/ApiService.js
> + * @return {object} - Response object.
давай везде напишем, что возвращается промис, который резолвится с ответом от бека, `object` не очень понятно

2020-11-07 08:53 UTC, gavroman commented on src/view/partnerLoginView.js
> +        this.root.innerHTML = template()
;

2020-11-07 08:53 UTC, gavroman commented on src/view/partnerLoginView.js
> +            this.eventBus.call('REDIRECT_TO_REG')
;

2020-11-07 08:53 UTC, gavroman commented on src/model/storeModel.js
> +                console.log(`Uncaught backend http-status: ${response.status}`);
а это точно по линтеру?

2020-11-07 08:53 UTC, gavroman commented on src/view/profileView.js
> +        console.log(data);
убираем

2020-11-07 08:53 UTC, gavroman commented on src/view/profileView.js
> +        seenBlock.classList.add("profile-page__navbar-button_focus");
если класс один и тот же, можно попробовать `classList.toggle()` - если класса у элемента не было, то он появится, если есть - исчезнет

2020-11-07 21:02 UTC, naysudes commented on src/view/profileView.js
> +        seenBlock.classList.add("profile-page__navbar-button_focus");
Попробовала переписать эту функцию, мне кажется, она более запутанно выглядит, если использовать classList.toggle()

2020-11-07 21:09 UTC, gavroman commented on src/view/profileView.js
> +        seenBlock.classList.add("profile-page__navbar-button_focus");
хорошо, не обязательно, так тоже норм, просто предложил, и теперь ты знаешь еще можно)

2020-11-08 10:39 UTC, gavroman requested changes

2020-11-08 10:39 UTC, gavroman commented on src/utils/ApiService.js
> +export const uploadPartnerAvatarRequest = (formAvatar) => {
а чем эта функция отличается от `uploadAvatarRequest`

2020-11-08 10:39 UTC, gavroman commented on src/utils/ApiService.js
> + * @param {object} avatarName - Picture name for request.
тут `avatarName` явно не `object`, давай поправим

2020-11-08 10:39 UTC, gavroman commented on src/utils/ApiService.js
> +        url: backendUrl + '/api/v1/sessions',
то же самое, есть же `loginRequest`

2020-11-08 10:39 UTC, gavroman commented on src/utils/ApiService.js
> +export const partnerRegisterRequest = (input) => {
тоже копипаста + неверное описание

2020-11-08 10:39 UTC, gavroman commented on src/utils/validator.js
> +    console.log(value);
выпиливаем

2020-11-08 11:47 UTC, merged