mvc заказов и навигация между заказами и магазином
frontend-park-mail-ru/2020_2_Friends pull request #35
Opened 2020-11-13 00:52 UTC by naysudes

Cделали статическую страничку магазина  и навигацию между магазином и этой страничкой

2020-11-13 07:22 UTC, gavroman requested changes

2020-11-13 07:22 UTC, gavroman commented on src/model/orderModel.js
> +            {
почему не так: `this.eventBus.call('SHOW_ORDERS', { storeId: id}` ?

2020-11-13 07:22 UTC, gavroman commented on src/template/orderViewTemplate.js
> +                    <p class="order-cart__address">Улица Пушкина, дом Кукушкинаaaaaaaaaaaaaaaaaaaaaaaaa</p>
когда перестанем хардкодить данные, что для этого нужно?

2020-11-16 08:01 UTC, gavroman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавление и удаление элементов из корзины](https://trello.com/c/H5PvwZic/48-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8-%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-%D0%B8%D0%B7-%D0%BA%D0%BE%D1%80%D0%B7%D0%B8%D0%BD%D1%8B)

2020-11-16 08:01 UTC, gavroman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Заказы](https://trello.com/c/kxOE6UbQ/46-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D1%8B)

2020-11-16 08:28 UTC, gavroman requested changes

2020-11-16 08:28 UTC, gavroman commented on .gitignore
> +.gitignore
не понял^ зачем гитигнор в гитигнор?

2020-11-16 08:28 UTC, gavroman commented on src/assets/css/profile_partners.css
> +    margin-right: auto;
2 раза `margin` в одном селекторе, и как работает `auto` если применить его только в одному отступу?

2020-11-16 08:28 UTC, gavroman commented on src/assets/css/store.css
> +    padding: 20px 0px 20px 0px;
`padding: 20px 0;`

2020-11-16 08:28 UTC, gavroman commented on src/model/bucketModel.js
> +        case 200: {
зачем `{}` в `case`?

2020-11-16 08:28 UTC, gavroman commented on src/model/partnerStoreModel.js
> +        const productInfo = { food_name: input.food_name, food_price: parseInt(input.food_price), food_id: input.food_id, store_id: input.store_id };
что если `input.food_price` не распарсится как число? Он возвращает NaN если не получилось распарсить

2020-11-16 08:28 UTC, gavroman commented on src/model/partnerStoreModel.js
> +            var data = input;
во-превых атата за вар, во-вторых - `data` же не используется

2020-11-16 08:28 UTC, gavroman commented on src/model/partnerStoreModel.js
> +            this.eventBus.call('RENDER_LOGO', { avatarUrl: avatarUrl });
можно просто  `this.eventBus.call('RENDER_LOGO', { avatarUrl }`

2020-11-16 08:28 UTC, gavroman commented on src/template/bucketViewTemplate.js
> +                <img class="bucket-item__img" src="http://89.208.197.247:9001/data/img/{{this.picture}}"></img>
давай будем `src` формировать полностью в модельке или вьюхе, где `http://89.208.197.247` будет браться из импортированной константы

2020-11-16 08:28 UTC, gavroman commented on src/template/orderViewTemplate.js
> +        <img src="http://89.208.197.247:9001/data/img/{{picture}}" class="store__logo" alt="Store logo">
тут тоже

2020-11-16 08:28 UTC, gavroman commented on src/template/partnerProfileViewTemplate.js
> +                    <img class="my-store__img" src="http://89.208.197.247:9001/data/img/{{this.picture}}"></img>
аналогично

2020-11-16 08:28 UTC, gavroman commented on src/template/partnerStoreViewTemplate.js
> +        <img src="http://89.208.197.247:9001/data/img/{{picture}}" class="store__logo" alt="Store logo">
и тут и дальше если есть

2020-11-16 08:28 UTC, gavroman commented on src/utils/ApiService.js
> +        url: backendUrl + '/api/v1/vendors/' + input.storeId + '/pictures',
давай везде будем одинаково делать, либо шаблонная строка, либо конкатенация через +

2020-11-16 08:28 UTC, gavroman commented on src/view/bucketView.js
> +        data.address = 'Москва, Красная площадь, дом 1';
почему опять хардкод?

2020-11-16 08:28 UTC, gavroman commented on src/view/partnerStoreView.js
> +        const descr = product.querySelector('.product__descr');
тут можно оставить, но дальше давай делать специальные селекторы для доставания из js, тип js-productDecr, чтобы классы для верстки можно было легко переименовывать

2020-11-16 15:20 UTC, naysudes commented on src/model/orderModel.js
> +            {
странно, этот метод в последнем комите выглядит совсем иначе

2020-11-16 15:20 UTC, naysudes commented on src/template/orderViewTemplate.js
> +                    <p class="order-cart__address">Улица Пушкина, дом Кукушкинаaaaaaaaaaaaaaaaaaaaaaaaa</p>
и тут

2020-11-16 15:28 UTC, naysudes commented on src/utils/ApiService.js
> +        url: backendUrl + '/api/v1/vendors/' + input.storeId + '/pictures',
+

2020-11-16 15:29 UTC, naysudes commented on src/view/partnerStoreView.js
> +        const descr = product.querySelector('.product__descr');
+

2020-11-16 15:30 UTC, naysudes commented on .gitignore
> +.gitignore
+

2020-11-16 15:30 UTC, naysudes commented on src/assets/css/profile_partners.css
> +    margin-right: auto;
+

2020-11-16 15:30 UTC, naysudes commented on src/assets/css/store.css
> +    padding: 20px 0px 20px 0px;
+

2020-11-16 15:31 UTC, naysudes commented on src/model/bucketModel.js
> +        case 200: {
обозначение блока, сейчас там одна строчка, но вообще нужна тут еще какая-то логика

2020-11-16 15:33 UTC, naysudes commented on src/model/partnerStoreModel.js
> +            var data = input;
Почему "атата"?

2020-11-16 16:02 UTC, naysudes commented on src/template/partnerProfileViewTemplate.js
> +                    <img class="my-store__img" src="http://89.208.197.247:9001/data/img/{{this.picture}}"></img>
+

2020-11-16 16:02 UTC, naysudes commented on src/template/orderViewTemplate.js
> +        <img src="http://89.208.197.247:9001/data/img/{{picture}}" class="store__logo" alt="Store logo">
+

2020-11-16 16:02 UTC, naysudes commented on src/template/bucketViewTemplate.js
> +                <img class="bucket-item__img" src="http://89.208.197.247:9001/data/img/{{this.picture}}"></img>
+

2020-11-16 16:02 UTC, naysudes commented on src/model/partnerStoreModel.js
> +            this.eventBus.call('RENDER_LOGO', { avatarUrl: avatarUrl });
+

2020-11-16 16:02 UTC, naysudes commented on src/template/partnerStoreViewTemplate.js
> +        <img src="http://89.208.197.247:9001/data/img/{{picture}}" class="store__logo" alt="Store logo">
+

2020-11-16 16:49 UTC, naysudes commented on src/view/bucketView.js
> +        data.address = 'Москва, Красная площадь, дом 1';
+

2020-11-16 16:52 UTC, naysudes commented on src/model/partnerStoreModel.js
> +        const productInfo = { food_name: input.food_name, food_price: parseInt(input.food_price), food_id: input.food_id, store_id: input.store_id };
+

2020-11-16 17:48 UTC, gavroman requested changes

2020-11-16 17:48 UTC, gavroman commented on src/model/partnerStoreModel.js
> +            var data = input;
потому что вар - это легаси, используем const и let

2020-11-16 17:48 UTC, gavroman commented on src/template/bucketViewTemplate.js
> +        </select>
понаехало

2020-11-16 17:48 UTC, gavroman commented on src/model/bucketModel.js
> +        case 200: {
case работает и без фигурных скобок, они нужны только если внутри объявлена переменная или константа

2020-11-16 17:48 UTC, gavroman commented on src/assets/css/order.css
> +    {
понаехало

2020-11-16 17:48 UTC, gavroman commented on src/model/partnerStoreModel.js
> +        const productInfo = { food_name: input.food_name, food_price: parseInt(input.food_price) ? parseInt(input.food_price) : 0, food_id: input.food_id, store_id: input.store_id };
![image](https://user-images.githubusercontent.com/48021024/99288409-9b1e1e80-284c-11eb-8b9d-269f1730c489.png)

2020-11-16 20:14 UTC, gavroman requested changes

2020-11-16 20:14 UTC, gavroman commented on src/view/partnerStoreView.js
> +            // priceErr.innerHTML = '';
раскоменчиваем или удаляем

2020-11-16 20:14 UTC, gavroman commented on src/model/partnerStoreModel.js
> +        if (!priceValidator.status) {
давай просто сделаем `!Number.isNaN(parseInt(foodPrice))`, регуляркой проверять на число как-то слишком жестоко)

2020-11-17 10:20 UTC, merged