Fix addresses
frontend-park-mail-ru/2020_2_Friends pull request #37
Opened 2020-11-15 23:46 UTC by naysudes

2020-11-15 23:47 UTC, naysudes commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавление адреса пользователя, удаление адреса (хотя бы просто скрыть)](https://trello.com/c/efrZjN9F/32-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B0%D0%B4%D1%80%D0%B5%D1%81%D0%B0-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F-%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B0%D0%B4%D1%80%D0%B5%D1%81%D0%B0-%D1%85%D0%BE%D1%82%D1%8F-%D0%B1%D1%8B-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE-%D1%81%D0%BA%D1%80%D1%8B%D1%82%D1%8C)

2020-11-16 07:59 UTC, gavroman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Заказы](https://trello.com/c/kxOE6UbQ/46-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D1%8B)

2020-11-16 08:31 UTC, gavroman requested changes

2020-11-16 08:31 UTC, gavroman commented on src/assets/css/order.css
> +    {
понаехало

2020-11-16 08:31 UTC, gavroman commented on src/model/bucketModel.js
> +        }
зачем `{}`

2020-11-17 16:24 UTC, gavroman requested changes

2020-11-17 16:24 UTC, gavroman commented on src/model/bucketModel.js
> +                { total: total, products: body, addresses: info.addresses });
понаехало

2020-11-17 16:24 UTC, gavroman commented on src/model/bucketModel.js
> +        console.log(body);
атата

2020-11-17 16:24 UTC, gavroman commented on src/model/bucketModel.js
> +            console.log(product.food_price);
атата

2020-11-17 16:24 UTC, gavroman commented on src/model/bucketModel.js
> +            console.log(product.food_price);
го сумму через `Array.prototype.reduce()`

2020-11-17 16:24 UTC, gavroman commented on src/model/profileModel.js
> +            console.log(addressValidator.status, addr);
атата

2020-11-17 16:24 UTC, gavroman commented on src/model/profileModel.js
> +            addressValidator = userFormValidator(data, regTemplates.address);
`const addressValidator`

2020-11-17 16:24 UTC, gavroman commented on src/view/profileView.js
> +        if (deleteBtns.length > 1) {
зочем

2020-11-17 16:24 UTC, gavroman commented on src/view/profileView.js
> +                addrs.push(addr.innerHTML);
`addrs = [addrsInput, ...oldAddrs]`

2020-11-17 16:24 UTC, gavroman commented on src/view/profileView.js
> +                addrs.push(addr.innerHTML);
func(...[1,2,3,4])
func(1,2,3,4)

2020-11-17 16:42 UTC, naysudes commented on src/assets/css/order.css
> +    {
+

2020-11-17 16:42 UTC, naysudes commented on src/model/bucketModel.js
> +        }
+

2020-11-17 16:43 UTC, naysudes commented on src/model/bucketModel.js
> +                { total: total, products: body, addresses: info.addresses });
+

2020-11-17 16:43 UTC, naysudes commented on src/model/bucketModel.js
> +        console.log(body);
+

2020-11-17 16:44 UTC, naysudes commented on src/model/profileModel.js
> +            console.log(addressValidator.status, addr);
+

2020-11-17 16:44 UTC, naysudes commented on src/model/profileModel.js
> +            addressValidator = userFormValidator(data, regTemplates.address);
+

2020-11-17 16:49 UTC, naysudes commented on src/view/profileView.js
> +        if (deleteBtns.length > 1) {
+

2020-11-17 16:59 UTC, naysudes commented on src/model/bucketModel.js
> +            console.log(product.food_price);
+

2020-11-17 21:15 UTC, gavroman requested changes

2020-11-17 21:15 UTC, gavroman commented on src/view/profileView.js
> +                const addrs = [...([...oldAddrs].map(oldAddr => oldAddr.innerText))];
тут можно сразу `[...oldAddrs].map(oldAddr => oldAddr.innerText)`, `Array.prototype.map()` и так возвращает массив

2020-11-17 21:36 UTC, merged