Added correct header work
frontend-park-mail-ru/2020_2_Friends pull request #38
Opened 2020-11-17 21:06 UTC by Scotfarel

Task in work, correct header done. Anything else?

https://trello.com/c/LAmYhPhf/31-%D0%BF%D1%80%D0%B8%D0%B4%D1%83%D0%BC%D0%B0%D1%82%D1%8C-%D0%BA%D0%B0%D0%BA-%D0%BE%D1%82%D0%BB%D0%B8%D1%87%D0%B0%D1%82%D1%8C-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B0-%D0%BE%D1%82-%D0%BD%D0%B5-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B0-%D0%BD%D0%B0-%D1%84%D1%80%D0%BE%D0%BD%D1%82%D0%B5

2020-11-17 21:07 UTC, Scotfarel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Придумать как отличать админа от не админа на фронте](https://trello.com/c/LAmYhPhf/31-%D0%BF%D1%80%D0%B8%D0%B4%D1%83%D0%BC%D0%B0%D1%82%D1%8C-%D0%BA%D0%B0%D0%BA-%D0%BE%D1%82%D0%BB%D0%B8%D1%87%D0%B0%D1%82%D1%8C-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B0-%D0%BE%D1%82-%D0%BD%D0%B5-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B0-%D0%BD%D0%B0-%D1%84%D1%80%D0%BE%D0%BD%D1%82%D0%B5)

2020-11-17 21:11 UTC, Scotfarel commented
ждем 403 от бека, и продолжаем работать, с вопросами разобрались

2020-11-17 21:26 UTC, Scotfarel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Придумать как отличать админа от не админа на фронте](https://trello.com/c/LAmYhPhf/31-%D0%BF%D1%80%D0%B8%D0%B4%D1%83%D0%BC%D0%B0%D1%82%D1%8C-%D0%BA%D0%B0%D0%BA-%D0%BE%D1%82%D0%BB%D0%B8%D1%87%D0%B0%D1%82%D1%8C-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B0-%D0%BE%D1%82-%D0%BD%D0%B5-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B0-%D0%BD%D0%B0-%D1%84%D1%80%D0%BE%D0%BD%D1%82%D0%B5)

2020-11-18 07:27 UTC, gavroman requested changes

2020-11-18 07:27 UTC, gavroman commented on src/index.js
> +    headerController.view.render(!isAdmin);
Ты смотрел, что приходит в эти функции? Они везде ждут boolean, а ты передаешь туда отрицание функции, то есть всегда false

2020-11-18 10:13 UTC, Scotfarel commented
исправил ошибку с передачей ф-и

2020-11-18 17:39 UTC, merged