редирект после заказа
frontend-park-mail-ru/2020_2_Friends pull request #39
Opened 2020-11-17 21:18 UTC by naysudes

2020-11-17 21:18 UTC, naysudes commented
![](https://github.trello.services/images/mini-trello-icon.png) [Редиректить в заказы после заказа](https://trello.com/c/vxnom5sZ/52-%D1%80%D0%B5%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%B8%D1%82%D1%8C-%D0%B2-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D1%8B-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0)

2020-11-18 20:36 UTC, gavroman requested changes

2020-11-18 20:36 UTC, gavroman commented on src/view/profileView.js
> +        this.addEventListeners();
а точно ли надо накидывать все обработчики? не все же кнопки есть на текущей странице

2020-11-18 20:36 UTC, gavroman commented on src/view/profileView.js
> +        this.addEventListeners();
разве для того, чтобы отрендерить нужную вкладку, нельзя просто вызвать changeSubPage?

2020-11-18 20:36 UTC, gavroman commented on src/view/profileView.js
> +        eventBus.subscribe('SHOW_PROFILE_ORDERS', this.showOrdersSubPage);
чет не очень получается, чем это событие отличается от `eventBus.subscribe('SHOW_ORDERS', this.showOrders);`

2020-11-18 20:36 UTC, gavroman commented on src/model/profileModel.js
> +    async getProfileOrdersData () {
чет не понял, чем эта функция отличается от getOrders

2020-11-19 18:52 UTC, naysudes commented on src/view/profileView.js
> +        eventBus.subscribe('SHOW_PROFILE_ORDERS', this.showOrdersSubPage);
SHOW_ORDERS вызывается уже при отрендеренном профиле и рисует только подстраничку заказы. SHOW_PROFILE_ORDERS рисует всю страничку профиля и страничку заказов.

2020-11-19 18:53 UTC, naysudes commented on src/view/profileView.js
> +        this.addEventListeners();
Нет, это две разные функции, все обработчики надо накидывать, потому что человек должен попадать на полностью функционирующую страничку профиля

2020-11-19 19:39 UTC, naysudes commented on src/model/profileModel.js
> +    async getProfileOrdersData () {
+

2020-11-19 21:00 UTC, naysudes commented on src/view/profileView.js
> +        eventBus.subscribe('SHOW_PROFILE_ORDERS', this.showOrdersSubPage);
переделала, теперь минимум копипасты

2020-11-19 21:00 UTC, naysudes commented on src/view/profileView.js
> +        this.addEventListeners();
переделано

2020-11-19 21:00 UTC, naysudes commented on src/model/profileModel.js
> +    async getProfileOrdersData () {
обсудили, переделано

2020-11-20 06:20 UTC, gavroman requested changes

2020-11-20 06:20 UTC, gavroman commented on src/view/profileView.js
> +        }
если в `switch case` нет объявления переменных, то `case` лучше без скобок, 2 } подряд выглядят страшно)

2020-11-20 06:20 UTC, gavroman commented on src/model/profileModel.js
> +                this.eventBus.call('SHOW_PROFILE_ORDERS', {
у `'SHOW_PROFILE_ORDERS'` и `'SHOW_PROFILE'` одинаковые данные, вьюха подписана на эти события функциями `render` и `showOrdersSubPage`, которые отличаются одной строчкой. Предлагаю оставить только `'SHOW_PROFILE'` и `render`, но прокидывать в него`subpage`, чтобы там сделать `this.сhangeSubPage(subpage);`

2020-11-20 06:20 UTC, gavroman commented on src/index.js
> +    headerController.view.render(false);
у нас теперь есть крутая функция `isAdmin()`

2020-11-20 10:43 UTC, naysudes commented on src/index.js
> +    headerController.view.render(false);
она не работает :(

2020-11-20 14:01 UTC, gavroman requested changes

2020-11-20 14:01 UTC, gavroman commented on src/assets/css/review.css
> +  .star-rating > span {
1) Понаехало
2) Сложные селекторы зло
3) Разве это к этой задаче?

2020-11-20 14:24 UTC, merged