заказы
frontend-park-mail-ru/2020_2_Friends pull request #46
Opened 2020-11-23 19:15 UTC by naysudes

то, что не дошло до дева

2020-11-23 20:26 UTC, gavroman requested changes

2020-11-23 20:26 UTC, gavroman commented on src/view/profileView.js
> +        reviewBtns.forEach(Btn => {
зачем с большой буквы

2020-11-23 20:26 UTC, gavroman commented on src/view/profileView.js
> +        document.getElementById('js-add-review').addEventListener('click', () => {
зачем стрелочная функция, можно так `addEventListener('click', this.createReview)`

2020-11-23 20:39 UTC, naysudes commented on src/view/profileView.js
> +        document.getElementById('js-add-review').addEventListener('click', () => {
+

2020-11-24 07:41 UTC, gavroman commented on src/view/profileView.js
> +        document.getElementById('js-add-review').addEventListener('click', () => {
почти, но так не будет работать. `addEventListener` 2 аргументом ждет функцию, а ты туда передаешь `undefined`

2020-11-24 12:16 UTC, gavroman requested changes

2020-11-24 12:16 UTC, gavroman commented on src/view/profileView.js
> +        offOverlay.addEventListener('click', () => {
тут тоже лишняя функция

2020-11-24 17:32 UTC, merged