Profile layout
frontend-park-mail-ru/2020_2_Friends pull request #5
Opened 2020-09-29 22:40 UTC by naysudes

2020-09-30 06:57 UTC, gavroman requested changes

2020-09-30 06:57 UTC, gavroman commented on static/main.css
> +a {
Не круто стилизовать все теги, лучше использовать классы. Селекторы по тегам можно применять если хочешь сбросить какие-то дефолтные стили браузера, погугли `reset.css`, во всех остальных случаях лучше использовать классы

2020-09-30 06:57 UTC, gavroman commented on static/main.css
> +    background: linear-gradient(to right, #2c5364, #203a43, #0f2027);
https://developer.mozilla.org/ru/docs/Web/CSS/:root
этот фон будет применяться ко всему документу вегда, а так как у вас SPA, то на других страницах он тоже будет. Если хочешь применять фон к всей своей странице, сделай обертку - дивак с классом profile_page и в него всю верстку

2020-09-30 06:57 UTC, gavroman commented on static/profile.css
> +    padding-right: 10em;
если пишешь все 4 падинга, то лучше сделать так: `padding: 10px 10em 10px 10px`

2020-09-30 06:57 UTC, gavroman commented on static/profile.css
> +    transform: translateY(0rem);
Не очень хорошо размечать элементы с помощью `translate`, давай попробуем сделать это другим способом

2020-09-30 06:57 UTC, gavroman commented on static/profile.css
> +    transform: translateY(-4rem);
тоже `translate`

2020-09-30 06:57 UTC, gavroman commented on static/profile.css
> +.form__input:placeholder-shown+.form__label {
по возможности стоит избегать сложных селекторов и везде использовать классы, и как минимум отделить + пробелами

2020-09-30 06:57 UTC, gavroman commented on static/profile.html
> +                <ul class="">
класс потерялся

2020-09-30 07:04 UTC, gavroman commented
Привет! Все круто, но есть пара общих замечаний:
1) Твоя ветка конфликтует с `dev`, влей ее в свою ветку (`git merge dev` из своей ветки)
2) Не очень понял нейминг классов, между словами есть - , _ и __. В этом есть какой-то смысл?
3) Лучше использовать одинаковые единицы измерения, это касается и `margin/padding` и цветов (`hex` или `rgb`)

О пунктах 2,3 лучше договориться 1 раз со всей командой и писать одинаково

2020-09-30 07:14 UTC, gavroman requested changes

2020-09-30 07:14 UTC, gavroman commented on static/profile.html
> +                            <input type="text" class="form__input" id="name" placeholder="Email" required="" />
айдишники должны быть уникальны в пределах всего документа

2020-09-30 19:13 UTC, naysudes commented on static/profile.css
> +    transform: translateY(-4rem);
Сделано

2020-09-30 19:13 UTC, naysudes commented on static/profile.css
> +    transform: translateY(0rem);
Сделано

2020-09-30 19:13 UTC, naysudes commented on static/profile.css
> +    padding-right: 10em;
Сделано

2020-09-30 19:14 UTC, naysudes commented on static/profile.html
> +                <ul class="">
Сделано

2020-09-30 19:14 UTC, naysudes commented on static/profile.css
> +.form__input:placeholder-shown+.form__label {
Сделано

2020-10-02 13:37 UTC, naysudes commented on static/main.css
> +    background: linear-gradient(to right, #2c5364, #203a43, #0f2027);
Оставлю, так как хочу дальше верстать странички и чтобы везде был одинаковый фон

2020-10-02 13:45 UTC, naysudes commented on static/main.css
> +a {
Сделано

2020-10-04 18:19 UTC, closed without merging