Map on creating store tab is visivble
frontend-park-mail-ru/2020_2_Friends pull request #51
Opened 2020-11-26 23:43 UTC by Scotfarel

Отрисовывается карта во вкладке создания магазина, пока все.
Но зато через какой-никакой класс. Постараюсь утром прикрутить считывание по ней адреса.

Потом займусь страницами всех магазинов и страницей одного магазина.

2020-11-27 15:25 UTC, gavroman commented on src/utils/mapAPI.js
> +        this.init = this.init.bind(this);
зачем 2 раза биндить?

2020-11-29 19:02 UTC, Scotfarel commented on src/utils/mapAPI.js
> +        this.init = this.init.bind(this);
убрал

2020-11-30 00:29 UTC, Scotfarel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Все что связано с картой](https://trello.com/c/OPICBfbZ/64-%D0%B2%D1%81%D0%B5-%D1%87%D1%82%D0%BE-%D1%81%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BE-%D1%81-%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D0%B9)

2020-11-30 00:29 UTC, Scotfarel commented
![](https://github.trello.services/images/mini-trello-icon.png) [На странице ресторана, отображать карту, центрованную по этому ресторану + его радиус обсуживания.](https://trello.com/c/xuK3oxeb/70-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D1%80%D0%B5%D1%81%D1%82%D0%BE%D1%80%D0%B0%D0%BD%D0%B0-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D1%82%D1%8C-%D0%BA%D0%B0%D1%80%D1%82%D1%83-%D1%86%D0%B5%D0%BD%D1%82%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%83%D1%8E-%D0%BF%D0%BE-%D1%8D%D1%82%D0%BE%D0%BC%D1%83-%D1%80%D0%B5%D1%81%D1%82%D0%BE%D1%80%D0%B0%D0%BD%D1%83-%D0%B5%D0%B3%D0%BE-%D1%80%D0%B0%D0%B4%D0%B8%D1%83%D1%81-%D0%BE%D0%B1%D1%81%D1%83%D0%B6%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

2020-11-30 00:29 UTC, Scotfarel commented
![](https://github.trello.services/images/mini-trello-icon.png) [На странице всех ресторанов отобразить карту](https://trello.com/c/2AMkPgNY/71-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D0%B2%D1%81%D0%B5%D1%85-%D1%80%D0%B5%D1%81%D1%82%D0%BE%D1%80%D0%B0%D0%BD%D0%BE%D0%B2-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%B8%D1%82%D1%8C-%D0%BA%D0%B0%D1%80%D1%82%D1%83)

2020-11-30 00:30 UTC, Scotfarel commented
![](https://github.trello.services/images/mini-trello-icon.png) [При создании магазина показывать карту](https://trello.com/c/S8ez0Fa4/72-%D0%BF%D1%80%D0%B8-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B8-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D0%B0-%D0%BF%D0%BE%D0%BA%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%BA%D0%B0%D1%80%D1%82%D1%83)

2020-11-30 07:36 UTC, gavroman requested changes
![image](https://user-images.githubusercontent.com/48021024/100579740-ccd7c080-32f5-11eb-8a1c-b0a605be5ee7.png)
этого тут быть не должно

2020-11-30 07:36 UTC, gavroman commented on src/assets/css/all_stores.css
> +    border-radius: 10px !important;
импортант нельзя

2020-11-30 07:36 UTC, gavroman commented on src/assets/css/profile_partners.css
> +    height: 400px
;

2020-11-30 07:36 UTC, gavroman commented on src/model/allStoresModel.js
> +                const body = await response.json();
не понял, почему 2 раза обрабатывается ответ? здесь и еще ниже свитч

2020-11-30 07:36 UTC, gavroman commented on src/model/storeModel.js
> +                body: body
почему выше достаются какие-то поля из body, а потом ты весь body прокидываешь?

2020-11-30 07:36 UTC, gavroman commented on src/utils/mapAPI.js
> +        });
давай тут и везде ниже повыравниваем, если параметров много, то пусть каждый будет с новой строки. Вот так хотябы 
![image](https://user-images.githubusercontent.com/48021024/100580636-5b990d00-32f7-11eb-96b4-70f3f6d8ef33.png)

2020-11-30 07:36 UTC, gavroman commented on src/utils/mapAPI.js
> +            var coords = e.get('coords');
почему вар?

2020-11-30 07:36 UTC, gavroman commented on src/utils/mapAPI.js
> +                    localStorage.setItem('newRestarauntCoordinate', coords);
зачем это в сторадж? почему нельзя в этом же классе сохраниить?

2020-11-30 07:36 UTC, gavroman commented on src/utils/mapAPI.js
> +            var firstGeoObject = res.geoObjects.get(0);
вар

2020-11-30 08:50 UTC, Scotfarel commented on src/assets/css/all_stores.css
> +    border-radius: 10px !important;
убрал

2020-11-30 08:51 UTC, Scotfarel commented on src/assets/css/profile_partners.css
> +    height: 400px
поправил

2020-11-30 08:56 UTC, Scotfarel commented on src/model/allStoresModel.js
> +                const body = await response.json();
ответил в тг

2020-11-30 08:57 UTC, Scotfarel commented on src/model/storeModel.js
> +                body: body
так было сделано, чтобы было удобно рендерить, а сейчас мне этот бади еще нужон при создании карты, не стал переделывать из-за этого то, что было

2020-11-30 09:09 UTC, Scotfarel commented on src/utils/mapAPI.js
> +            var coords = e.get('coords');
const

2020-11-30 09:10 UTC, Scotfarel commented on src/utils/mapAPI.js
> +        });
ispravil

2020-11-30 09:13 UTC, Scotfarel commented on src/utils/mapAPI.js
> +                    localStorage.setItem('newRestarauntCoordinate', coords);
потому что потом координаты мне нужны будут во вьюхе, чтобы по нажатию на кнопку отправить массив со всеми данными, и чтобы не искать очень неочевидных путей по проброске атрибутов инстанса, я решил использовать в этом месте локалсторадж, я так сделал 1 раз за проект, надеюсь это норм

2020-11-30 09:13 UTC, Scotfarel commented on src/utils/mapAPI.js
> +            var firstGeoObject = res.geoObjects.get(0);
const

2020-11-30 09:19 UTC, Scotfarel commented on src/assets/css/all_stores.css
> +    border-radius: 10px !important;
убрал

2020-11-30 09:20 UTC, Scotfarel commented on src/assets/css/profile_partners.css
> +    height: 400px
добавил

2020-11-30 09:57 UTC, merged