Making chat
frontend-park-mail-ru/2020_2_Friends pull request #53
Opened 2020-11-29 14:41 UTC by naysudes

Чатик в рабочем состоянии

2020-11-29 14:43 UTC, naysudes commented
![](https://github.trello.services/images/mini-trello-icon.png) [Чатик](https://trello.com/c/3CLmQ7c9/65-%D1%87%D0%B0%D1%82%D0%B8%D0%BA)

2020-11-29 14:45 UTC, gavroman commented on src/assets/css/main.css
> +    background: #dd9d88 !important;
Ататата, имортант не хорошо

2020-11-29 15:00 UTC, gavroman requested changes

2020-11-29 15:00 UTC, gavroman commented on src/controller/chatController.js
> +     * Creating controller class for header entity.
Описание не соответствует

2020-11-29 15:00 UTC, gavroman commented on src/utils/Socket.js
> +            this.socketTimer = setInterval(() => this.socket.send(''), 10000);
А это зачем?

2020-11-29 15:00 UTC, gavroman commented on src/utils/Socket.js
> +        if (connectionState === WebSocket.CLOSED || connectionState === WebSocket.CLOSING) {
Что за пустой ифак

2020-11-29 15:00 UTC, gavroman commented on src/utils/Socket.js
> +        case 'message':
Зачем свитч на 1 кейс

2020-11-29 15:00 UTC, gavroman commented on src/view/profileView.js
> +                newMessage.dataset.id = id;
А это точно работает? Если да, то зачем так?

2020-11-29 15:09 UTC, naysudes commented on src/controller/chatController.js
> +     * Creating controller class for header entity.
+

2020-11-29 15:10 UTC, naysudes commented on src/utils/Socket.js
> +        if (connectionState === WebSocket.CLOSED || connectionState === WebSocket.CLOSING) {
Если в других  mvc уже приконекчен сокет, не конектим его повторно

2020-11-29 15:11 UTC, naysudes commented on src/utils/Socket.js
> +        case 'message':
+

2020-11-29 15:13 UTC, naysudes commented on src/view/profileView.js
> +                newMessage.dataset.id = id;
Работает, зачем так - обсудили

2020-11-29 15:17 UTC, naysudes commented on src/utils/Socket.js
> +            this.socketTimer = setInterval(() => this.socket.send(''), 10000);
чтобы сокет по таймауту не отлетал

2020-11-29 15:24 UTC, naysudes commented on src/assets/css/main.css
> +    background: #dd9d88 !important;
+

2020-11-30 06:54 UTC, gavroman commented on src/view/profileView.js
> +                console.log(btn);
убаираем

2020-11-30 06:54 UTC, gavroman commented on src/view/chatView.js
> +                console.log(newMessage);
логи

2020-11-30 06:56 UTC, gavroman commented on src/model/registerModel.js
> +import webSocket from '../utils/Socket.js';
давай еще пустую строку добавим

2020-11-30 06:57 UTC, gavroman commented on src/utils/Socket.js
> +        if (connectionState === WebSocket.CLOSED || connectionState === WebSocket.CLOSING) {
это понятно, но зачем пустой ифак, а логика в else?

2020-11-30 07:01 UTC, gavroman commented on src/utils/Socket.js
> +        if (connectionState === WebSocket.CLOSED || connectionState === WebSocket.CLOSING) {
почему не если не закрыт и не закрывается, то закрываем

2020-11-30 08:48 UTC, naysudes commented on src/view/profileView.js
> +                console.log(btn);
+

2020-11-30 08:48 UTC, naysudes commented on src/view/chatView.js
> +                console.log(newMessage);
+

2020-11-30 08:49 UTC, naysudes commented on src/model/registerModel.js
> +import webSocket from '../utils/Socket.js';
+

2020-11-30 08:52 UTC, naysudes commented on src/utils/Socket.js
> +        if (connectionState === WebSocket.CLOSED || connectionState === WebSocket.CLOSING) {
Если он уже закрывается - это то, что мы хотим (функция дисконект), если бы мы не проверяли, то попытались бы два раза закрыть сокет, что не ок

2020-11-30 09:15 UTC, gavroman commented on src/view/bucketView.js
> +        delItemBtn.forEach(btn => { btn.click(); });
а это зачем?

2020-11-30 10:32 UTC, gavroman commented on src/view/bucketView.js
> +        products.forEach(item => {
в data.profucts уже хранятся все айдишники, почему не по ним цикл?

2020-11-30 10:39 UTC, merged